# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name las
#' @rdname las
#' @section Rule:
#' When `rule = "interesection"` or `rule = "i"`, the union method is used.
#' A tie is marked as present iff both i and j agree on the existance if (i,j).
NULL

#' @name las
#' @rdname las
#' @section Rule:
#' When `rule = "union"` or `rule = "u"`, the union method is used. In such case
#' a tie is marked as present if any of the individuals declares it.
NULL

#' @name las
#' @rdname las
#' @section Rule:
#' When `rule = "threshold"` or `rule = "t"`, the threshold method is used in which
#' a tie is marked as present iff the proportion of individuals who agree on the
#' existance of that is greater than `threshold`. In its paper, Krackhardt calls
#' this *Concensus Structure* (CS).
NULL

.las <- function(M, rule, threshold = 1, self = FALSE) {
    .Call(`_similR_las`, M, rule, threshold, self)
}

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Jaccard (1): `"sjaccard"` or `"jaccard"`
#' @aliases Jaccard
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Tarwid (54): `"starwid"` or `"tarwid"`.
#' @aliases Tarwid
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' -  Pearson & Heron 1 (54): `"sph1"` or `"ph1"` or `"s14"`. This is also known as S14 in
#'    Gower and Legendre (1986).
#'    
#'    In the case of the `S14` function, following Krackhardt's 1989:
#'    
#'    \deqn{%
#'    \sqrt{\left(\frac{a}{(a + c)} - \frac{b}{(b + d)}\right)\times\left(\frac{a}{(a + b)} - \frac{c}{(c + d)}\right)}
#'    }{%
#'    S14 = [(a/(a + c) - b/(b + d))*(a/(a + b) - c/(c + d))]^(1/2)
#'    }
#'   
#'    Which is an statistic lying between 0 and 1.
#'  
#' @aliases Person-&-Heron
#' @aliases S14
NULL

#' @name similarity
#' @rdname similarity
#' @section Distance:
#' - Hamming (15): `"dhamming"` or `"hamming"`
#' @aliases Hamming
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Dennis (44): `"sdennis"` or `"dennis"`
#' @aliases Dennis
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Yuleq (61): `"syuleq"`
#' @aliases Yuleq
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Yuleq (63): `"syuleqw"`
#' @aliases Yuleq
NULL

#' @name similarity
#' @rdname similarity
#' @section Distance:
#' - Yuleq (62): `"dyuleq"`
#' @aliases Yuleq
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Michael (68):  `"smichael"` or `"michael"`
#' @aliases Michael
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Peirce (73): `"speirce"` or `"peirce"`
#' @aliases Peirce
NULL

.similarity <- function(M, statistic, normalized = FALSE) {
    .Call(`_similR_similarity`, M, statistic, normalized)
}

