# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name las
#' @rdname las
#' @section Rule:
#' When `rule = "interesection"` or `rule = "i"`, the union method is used.
#' A tie is marked as present iff both i and j agree on the existance if (i,j).
NULL

#' @name las
#' @rdname las
#' @section Rule:
#' When `rule = "union"` or `rule = "u"`, the union method is used. In such case
#' a tie is marked as present if any of the individuals declares it.
NULL

#' @name las
#' @rdname las
#' @section Rule:
#' When `rule = "threshold"` or `rule = "t"`, the threshold method is used in which
#' a tie is marked as present iff the proportion of individuals who agree on the
#' existance of that is greater than `threshold`. In its paper, Krackhardt calls
#' this *Concensus Structure* (CS).
NULL

.las <- function(M, rule, threshold = 1, self = FALSE) {
    .Call(`_similR_las`, M, rule, threshold, self)
}

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Jaccard (1): `"sjaccard"` or `"jaccard"`
#' @aliases Jaccard
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Faith (10): `"sfaith"` or `"faith"`
#' @aliases Faith
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Gower & Legendre (11): `"sgl"` or `"gl"`
#' @aliases Gower-&-Legendre
NULL

#' @name similarity
#' @rdname similarity
#' @section Distance:
#' - Sized Difference (24): `"dsd"` or `"sd"`
#' @aliases Sized-Difference
NULL

#' @name similarity
#' @rdname similarity
#' @section Distance:
#' - Shaped Difference (25): `"dsphd"` or `"sphd"`
#' @aliases Shape-Difference
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Tarwid (54): `"starwid"` or `"tarwid"`.
#' @aliases Tarwid
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' -  Pearson & Heron 1 (54): `"sph1"` or `"ph1"` or `"s14"`. This is also known as S14 in
#'    Gower and Legendre (1986).
#'    
#'    In the case of the `S14` function, following Krackhardt's 1989:
#'    
#'    \deqn{%
#'    \sqrt{\left(\frac{a}{(a + c)} - \frac{b}{(b + d)}\right)\times\left(\frac{a}{(a + b)} - \frac{c}{(c + d)}\right)}
#'    }{%
#'    S14 = [(a/(a + c) - b/(b + d))*(a/(a + b) - c/(c + d))]^(1/2)
#'    }
#'   
#'    Which is an statistic lying between 0 and 1.
#'  
#' @aliases Person-&-Heron
#' @aliases S14
NULL

#' @name similarity
#' @rdname similarity
#' @section Distance:
#' - Hamming (15): `"dhamming"` or `"hamming"`
#' @aliases Hamming
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' -  Mean Manhattan (20): `"dmh"` or `"mh"`
#'    \deqn{%
#'      D_{Mean-manhattan} = \frac{b + c}{a + b + c + d}
#'    }{%
#'     dmh = (b + c)/(a + b + c + d)
#'    }
#' @aliases Mean-Manhattan
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Dennis (44): `"sdennis"` or `"dennis"`
#' @aliases Dennis
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Yuleq (61): `"syuleq"`
#' @aliases Yuleq
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' - Yuleq (63): `"syuleqw"`
#' @aliases Yuleq
NULL

#' @name similarity
#' @rdname similarity
#' @section Distance:
#' - Yuleq (62): `"dyuleq"`
#' @aliases Yuleq
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' -  Michael (68):  `"smichael"` or `"michael"`
#'    
#'    \deqn{%
#'      S_{michael} = \frac{4(ad-bc)}{(a+d)^2 + (b+c)^2}
#'    }{%
#'      smichael = 4*(a*d - b*c)/[(a + d)^2 + (b + c)^2]
#'    }
#' @aliases Michael
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' -  Dispersion (66):  `"sdisp"` or `"disp"`
#'    
#'    \deqn{%
#'      S_{Dispersion} = \frac{ad - bc}{(a + b + c + d)^2}
#'    }{%
#'      sdisp = [a*d - b*c]/(a + b + c + d)^2
#'    }
#' @aliases Dispersion
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' -  Hamann (67):  `"shamann"` or `"hamann"`
#'    
#'    \deqn{%
#'      S_{Hamann} = \frac{(a + d) - (b + c)}{a + b + c + d}
#'    }{%
#'      shamann = [(a + d) - (b + c)](a + b + c + d)
#'    }
#' @aliases Hamann
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' -  Goodman & Kruskal (69): `"sgk"` or `"gk"`
#'    
#'    \deqn{%
#'      S_{Goodman&Kruskal} = \frac{\sigma - \sigma'}{2n - \sigma'} 
#'    }{%
#'      sgk = (s + s')/(2*n - s') 
#'    }
#'    
#'    where
#'    \eqn{\sigma = \max(a,b) + \max(c,d) + \max(a,c) + \max(b,d)}{
#'    s = max(a,b) + max(c,d) + max(a,c) + max(b,d)
#'    }, and 
#'    \eqn{\sigma' = \max(a + c, b + d) + \max(a + b, c + d)}{
#'    s' = max(a + c, b + d) + max(a + b, c + d)
#'    }
#'   
#' @aliases Goodman-&-Kruskal
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' -  Anderberg (70): `"sanderberg"` or `"anderberg"`
#'    
#'    \deqn{%
#'      S_{Anderberg} = \frac{\sigma - \sigma'}{2n} 
#'    }{%
#'      sanderberg = (s + s')/(2*n) 
#'    }
#'    
#'    where \eqn{\sigma}{s} and \eqn{\sigma}{s'} are defined as in (69).
#'   
#' @aliases Anderberg
NULL

#' @name similarity
#' @rdname similarity
#' @section Similarity:
#' -  Peirce (73): `"speirce"` or `"peirce"`
#'    
#'    \deqn{%
#'      S_{Peirce} = \frac{ab + bc}{ab + 2bc + cd}
#'    }{%
#'      speirce = (a*b + b*c)/(a*b + 2*b*c + c*d)
#'    }
#'   
#' @aliases Peirce
NULL

reduce_dim <- function(x, k) {
    .Call(`_similR_reduce_dim`, x, k)
}

.similarity <- function(M, statistic, normalized = FALSE, firstonly = FALSE, exclude_j = FALSE) {
    .Call(`_similR_similarity`, M, statistic, normalized, firstonly, exclude_j)
}

