# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_sets <- function(n) {
    .Call(`_lergm_make_sets`, n)
}

.powerset <- function(n, force = FALSE) {
    .Call(`_lergm_powerset`, n, force)
}

.S14 <- function(M) {
    .Call(`_lergm_S14`, M)
}

