# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_mutual <- function(x) {
    .Call(`_ergmito_count_mutual`, x)
}

count_edges <- function(x) {
    .Call(`_ergmito_count_edges`, x)
}

count_stats. <- function(X, terms) {
    .Call(`_ergmito_count_stats`, X, terms)
}

exact_loglik. <- function(x, params, weights, statmat, as_prob = FALSE) {
    .Call(`_ergmito_exact_loglik`, x, params, weights, statmat, as_prob)
}

make_sets <- function(n) {
    .Call(`_ergmito_make_sets`, n)
}

.powerset <- function(n, force = FALSE) {
    .Call(`_ergmito_powerset`, n, force)
}

print_powerset <- function(sets) {
    .Call(`_ergmito_print_powerset`, sets)
}

wrap_powerset <- function(sets, from, to, n) {
    .Call(`_ergmito_wrap_powerset`, sets, from, to, n)
}

