---
title: Social Smarts
author:
  - de la Haye, Kayla
  - Labrecque, Jennifer
  - Vega Yon, George
date: Version `r Sys.time()`
output: pdf_document
---

A graph is a tuple $G = (V, E)$ with $n$ vertices and $m$ edges.

Graphs can be represented as adjencency matrices $A = A(G) = \left\{a_{ij}\right\}$
with $a_{ij} = 1$ if $(i,j) \in E$.

Cognitive Social Structure (CSS) for individual $i$ is what the individual thinks $A$
looks like. We denote the CSS of $i$ as $A^i=\{a_{lk}^i\}$ with $a_{lk}^i$ equal
to 1 if $i$ thinks that a tie from $l$ to $k$ exists.

Hamming distance is given by $H_{ij} = \sum_{h,k} \mathbf{1}\left(a^i_{hk} \neq a^j_{hk}\right)$

We define the infered social structure as follows $\hat A(G) = \left\{a_{ij}\right\}$,
where $a_{ij} = \mathbf{1}\left(a^i_{ij} = a^j_{ij}\right)$, i.e. if both $i$ and
$j$ agree in the existance of such tie.

# Simulation model

Each team's performance level, call it $Y$, has a binomial distribution with
parameters $M$ and $p$, where $M$ is the maximum number of correct tasks done and
$p = \mbox{logit}(\theta^\mathbf{t}g(X, G))$.

The idea is that $g(X,G)$ can be a set of statistics defined by both the graph and
groups' features such as number of triads, and so on.

