---
title: "Little ERGMs"
author:
    - George G. Vega Yon
    - Kayla de la Haye
date: Oct 19th, 2018
output:
  beamer_presentation:
    slide_level: 2 # revealjs::revealjs_presentation
    highlight: espresso
    latex_engine: xelatex
header-includes:
  - \usefonttheme{professionalfonts}
  - \usefonttheme{serif}
  - \usepackage{fontspec}
  - \setmainfont{TeX Gyre Heros}
  - \setbeamerfont{note page}{family*=pplx,size=\footnotesize}
---

## Context

*   We have 4 teams with 3 to 5 individuals.

*   We have information about the individuals (gender, age, GPA, etc.)

*   Individuals were randomly assigned to teams with the criterion that there was at least one male and one female per group

*   Each team was asked to perform a series of 12 group tasks (using 2 versions of MIT's Test for Collective Intelligence); and each teammate individually reported on (A) a comprehensive measure of personality, and emotional/social intelligence, and (B) their perceptions of the team social network  (multiplex tie)s

We would like to be able to estimate ERGM models here.

## The problem with Small networks

*   MCMC breaks (no convergence) when trying to estimate a block diagonal model,

*   Same happens when trying to estimate an ERGM for a single graph

*   Even if it converges, the Asymptotic properties of MLEs are no longer valid
    since the sample size is not large enough.
    
## Rethinking the problem

*   1st Approach: Forget about MCMC-MLE estimation, take advantage of small
    sample and use exact statistic for MLEs.

--------

\footnotesize

```{r}
library(lergm)
set.seed(12)
x <- sna::rgraph(4)
summary(lergm(x~edges + balance))
```

\normalsize

----------

*   Cool, we are able to estimate ERGMs for little networks! (we actually call
    them lERGMs), but...
    
*   We still have issues regarding asymptotics.

But there's some light at the end of the path...

## Solution

*   Remember that we were trying to estimate a block diagonal ERGM?
    
    We were essentially assuming independence across teams

*   This means that we can actually do the same with exact statistics
    
    $$
    \Pr\left(\mathbf{Y}={\color{cyan} \{}\mathbf{y}_{\color{cyan} i}{\color{cyan} \}}|\theta, \mathcal{Y}\right) = {\color{cyan} \prod_i} \frac{\exp{\theta^{\mbox{T}}\mathbf{g}(\mathbf{y}_{\color{cyan} i})}}{\kappa\left(\theta, \mathcal{Y}\right)}
    $$
    
*   By estimating a pulled version of the ERGM (which is equivalent to block diagonal),
    we can recover the asymptotics of MLEs.
    
## Discussion

*   This is no panacea: The external validity lERGMs inference is yet more complicated than ERGMs.

*   Small structures yield a smaller pool of parameters... unless we use nodes' covariates (otherwise the model is not ~~very~~ informative)



*   We could actually go further and think about Separable Exponential Random Graph Models (aka TERGMs)... this could be an interesting approach 